"""Transaction model fix

Revision ID: 2d06fdea31c8
Revises: b1953f568976
Create Date: 2024-11-30 00:27:25.729916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d06fdea31c8'
down_revision: Union[str, None] = 'b1953f568976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cable_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'cables', ['cable_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'cable_id')
    # ### end Alembic commands ###
