"""Users model fix

Revision ID: 881e138da75c
Revises: 4e448c8582ac
Create Date: 2024-11-29 23:58:18.081478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881e138da75c'
down_revision: Union[str, None] = '4e448c8582ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cables', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'cables', type_='unique')
    # ### end Alembic commands ###
