services:
  db:
    image: postgres:15
    container_name: dcs_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-docker
    ports:
      - 5432

  redis:
    image: redis
    container_name: dcs_redis

  server:
    build:
      context: .
    container_name: dcs_app
    env_file:
      - .env-docker
    depends_on:
      - db
      - redis
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"  # TO DO: Сменить на gunicorn
    ports:
      - 8000:8000

  celery:
    image: dcs_celery
    build:
      context: . 
    container_name: dcs_celery
    command: celery --app=app.tasks.celery:celery worker -l INFO
    env_file:
      - .env-docker
    depends_on:
      - redis

  flower:
    image: dcs_flower
    build:
      context: . 
    container_name: dcs_flower
    command: celery --app=app.tasks.celery:celery flower
    env_file:
      - .env-docker
    depends_on:
      - redis
    ports:
      - 5555:5555
      
volumes:
  postgresdata:
