"""Initial DB

Revision ID: 39863ba1d180
Revises: 
Create Date: 2024-11-23 11:08:30.769054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39863ba1d180'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cables',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('assembly', sa.String(), nullable=False),
    sa.Column('factory_number', sa.String(), nullable=False),
    sa.Column('last_service', sa.DateTime(), nullable=False),
    sa.Column('next_service', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'GIVEN', 'ON_SERVICE', name='cablestatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdb_storage',
    sa.Column('division', sa.Enum('LAB1', 'LAB2', 'LAB3', 'LAB5', 'LAB6', 'LAB7', 'LAB8', 'PDB', name='divisionenum'), server_default='PDB', nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('division', sa.Enum('LAB1', 'LAB2', 'LAB3', 'LAB5', 'LAB6', 'LAB7', 'LAB8', 'PDB', name='divisionenum'), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userroleenun'), server_default='USER', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factory_employee_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_table('pdb_storage')
    op.drop_table('cables')
    # ### end Alembic commands ###
